/**
 * Builds dist/tokens.css from tokens.json (canonical DTCG source).
 *
 * Output contract (consumed by @courvia/ui and apps/web):
 * - Global primitives on `:root` as `--cv-<path>` (e.g. --cv-color-volt-400).
 * - One block per theme keyed by the short `data-theme` alias
 *   (volt | carbon | club). The default theme (volt, dark-first) is also
 *   applied to bare `:root` so a page never renders unthemed.
 * - Theme values that reference a global token emit `var(--cv-...)` so the
 *   CSS keeps a single source per primitive; literals emit as-is.
 */
import { referencePath, resolveToken } from "./resolve";
import { THEME_ALIASES, isToken } from "./types";
import type {
  ShadowValue,
  Token,
  TokenGroup,
  TokensDocument,
} from "./types";

// Re-exported because the pure resolver used to live in this module, and its
// tests — plus the semantic-contract suite — import it from here.
export { lookupToken, resolveToken } from "./resolve";

const PREFIX = "--cv";
/** Generic CSS font families that must not be quoted. */
const GENERIC_FAMILIES = new Set([
  "serif",
  "sans-serif",
  "monospace",
  "cursive",
  "fantasy",
  "system-ui",
]);

export interface FlatToken {
  /** Dot path inside its group, e.g. "color.court.950" */
  path: string;
  token: Token;
}

export function flattenGroup(group: TokenGroup, base = ""): FlatToken[] {
  const out: FlatToken[] = [];
  for (const [key, node] of Object.entries(group)) {
    const path = base === "" ? key : `${base}.${key}`;
    if (isToken(node)) {
      out.push({ path, token: node });
    } else {
      out.push(...flattenGroup(node, path));
    }
  }
  return out;
}

/** "color.court.950" -> "--cv-color-court-950" */
export function cssVarName(path: string): string {
  return `${PREFIX}-${path.split(".").join("-")}`;
}

function fontFamilyCss(families: string[]): string {
  return families
    .map((f) => (GENERIC_FAMILIES.has(f) ? f : `'${f}'`))
    .join(", ");
}

function shadowCss(shadow: ShadowValue): string {
  return `${shadow.offsetX} ${shadow.offsetY} ${shadow.blur} ${shadow.spread} ${shadow.color}`;
}

function assertNoEmbeddedReference(value: string, context: string): string {
  if (value.includes("{")) {
    throw new Error(
      `References inside composite values are not supported (${context}: "${value}")`,
    );
  }
  return value;
}

/** Literal (already resolved) token value -> CSS value text. */
export function cssValue(token: Token): string {
  switch (token.$type) {
    case "color":
    case "dimension":
    case "duration":
      return String(token.$value);
    case "number":
      return String(token.$value);
    case "cubicBezier":
      return `cubic-bezier(${(token.$value as number[]).join(", ")})`;
    case "fontFamily":
      return fontFamilyCss(
        (token.$value as string[]).map((f) => assertNoEmbeddedReference(f, "fontFamily")),
      );
    case "shadow": {
      const shadow = token.$value as ShadowValue;
      for (const [key, part] of Object.entries(shadow)) {
        assertNoEmbeddedReference(part, `shadow.${key}`);
      }
      return shadowCss(shadow);
    }
    default:
      throw new Error(`Unsupported token $type: "${String(token.$type)}"`);
  }
}

/**
 * CSS text for one theme token: references to global tokens become var()
 * chains; anything else resolves to a literal.
 */
export function themeValueCss(doc: TokensDocument, token: Token): string {
  const ref = referencePath(token.$value);
  if (ref !== null && ref.startsWith("global.")) {
    // Validate the target exists even though we emit an indirection.
    resolveToken(doc, token);
    return `var(${cssVarName(ref.slice("global.".length))})`;
  }
  return cssValue(resolveToken(doc, token));
}

function declarations(lines: string[]): string {
  return lines.map((l) => `  ${l}`).join("\n");
}

export function buildCss(doc: TokensDocument): string {
  const blocks: string[] = [
    "/* Generated by @courvia/design-tokens — do not edit by hand.",
    " * Source of truth: tokens.json (mirror of brand/courvia-tokens.json). */",
  ];

  const globalLines = flattenGroup(doc.global).map(
    ({ path, token }) => `${cssVarName(path)}: ${cssValue(resolveToken(doc, token))};`,
  );
  blocks.push(`:root {\n${declarations(globalLines)}\n}`);

  // Union of variable paths across themes: a theme that does not define a
  // path neutralizes it with `initial` (guaranteed-invalid), so var() usages
  // fall back to their declared fallback instead of inheriting another
  // theme's value (e.g. volt's --cv-font-data leaking into club via :root).
  const flatThemes = new Map(
    Object.entries(THEME_ALIASES).map(([alias, themeKey]) => {
      const group = doc.theme[themeKey];
      if (group === undefined) {
        throw new Error(`tokens.json is missing theme "${themeKey}"`);
      }
      return [alias, flattenGroup(group)] as const;
    }),
  );
  const unionPaths = new Set(
    [...flatThemes.values()].flatMap((tokens) => tokens.map(({ path }) => path)),
  );

  for (const [alias, tokens] of flatThemes) {
    const ownPaths = new Set(tokens.map(({ path }) => path));
    const lines = tokens.map(
      ({ path, token }) => `${cssVarName(path)}: ${themeValueCss(doc, token)};`,
    );
    for (const path of unionPaths) {
      if (!ownPaths.has(path)) lines.push(`${cssVarName(path)}: initial;`);
    }
    // volt is the dark-first default: bare :root gets it too (no FOUC on
    // pages that have not set data-theme yet). Later equal-specificity theme
    // blocks override when the attribute is present.
    const selector =
      alias === "volt" ? `:root,\n[data-theme='${alias}']` : `[data-theme='${alias}']`;
    blocks.push(`${selector} {\n${declarations(lines)}\n}`);
  }

  return blocks.join("\n\n") + "\n";
}

/* CLI entry: tsx src/build-css.ts */
if (process.argv[1] !== undefined && import.meta.url === (await import("node:url")).pathToFileURL(process.argv[1]).href) {
  const { readFile, mkdir, writeFile } = await import("node:fs/promises");
  const { fileURLToPath } = await import("node:url");
  const { dirname, join } = await import("node:path");

  const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
  const doc = JSON.parse(
    await readFile(join(pkgRoot, "tokens.json"), "utf8"),
  ) as TokensDocument;
  const css = buildCss(doc);
  await mkdir(join(pkgRoot, "dist"), { recursive: true });
  await writeFile(join(pkgRoot, "dist", "tokens.css"), css, "utf8");
  console.log(`tokens.css written (${css.length} bytes)`);
}
