/**
 * The picture a section shows in the block picker.
 *
 * WHY A WIREFRAME AND NOT A SCREENSHOT. The obvious idea is to photograph
 * the seeded demo page and crop one band per section. Payload's own drawer
 * says why that loses: `blocks-drawer__blocks` is a six-column grid
 * (@payloadcms/ui .../BlockSelector/index.scss), so a tile is ~140px wide
 * and ~93px tall, with `object-fit: cover`. A 480x320 photograph of a real
 * band arrives there as a smudge in which stage, hero and ctaBand are
 * indistinguishable — which is the exact question the tile has to answer.
 * A wireframe at that size still reads: full-bleed media, two columns, a
 * grid of four, a rail of milestones.
 *
 * The second reason is that a screenshot pipeline could not run in CI. This
 * repo has no browser and no Playwright; screenshots would be files someone
 * regenerated by hand, drifting from the sections the moment one changed —
 * "capturas sueltas" with extra steps. A sketch is code: it is generated on
 * every boot, it is covered by tests, and it cannot be stale.
 *
 * WHAT KEEPS IT FROM BEING "drawn icons". A sketch is not free drawing: it
 * is a closed vocabulary of ROLES on a 12x8 grid, and every role resolves to
 * a real token of the default theme through `themeColor` — the same route
 * the Open Graph card takes for the same reason (a surface that renders no
 * stylesheet still has to be on-brand). Re-theme the tokens and every
 * thumbnail re-skins itself. No hex is written here.
 */
import tokens from "@courvia/design-tokens/tokens.json";
import { DEFAULT_THEME, themeColor } from "@courvia/design-tokens";
import type { TokensDocument } from "@courvia/design-tokens";

const DOC = tokens as TokensDocument;

/** 3:2 exactly, which is the ratio the drawer tile declares — authoring to
 *  it means `object-fit: cover` has nothing to crop. */
export const THUMBNAIL_SIZE = { width: 480, height: 320 } as const;

/** The sketch grid. 12 x 8 over 480 x 320 makes one unit a round 40px. */
export const SKETCH_GRID = { columns: 12, rows: 8 } as const;

const UNIT = THUMBNAIL_SIZE.width / SKETCH_GRID.columns;

/**
 * What a rectangle MEANS, not what colour it is. The vocabulary is closed
 * for the same reason the appearance controls are: a sketch that could name
 * a colour would be a second, unaudited palette.
 */
export const SKETCH_ROLES = {
  /** A panel: card, table body, form. */
  surface: "surface",
  /** A panel that sits above the last one. */
  raised: "surface-raised",
  /** Image or video standing in for the real asset. */
  media: "border",
  /** Anything the accent fills: primary button, chip, active marker. */
  accent: "accent",
  /** Type and buttons ON an accent fill. The pair exists because a band
   *  filled with the accent has to invert, exactly as `background: accent`
   *  does at render time — a tile that ignored that would be a lie. */
  onAccent: "accent-contrast",
  /** A line of heading-weight type. */
  text: "text",
  /** A line of body type. */
  muted: "text-muted",
  /** A hairline: divider, rail, table rule. */
  rule: "border",
} as const;

export type SketchRole = keyof typeof SKETCH_ROLES;

export interface SketchShape {
  role: SketchRole;
  /** Grid units from the inline start. */
  x: number;
  /** Grid units from the block start. */
  y: number;
  w: number;
  h: number;
  /** `soft` is a card corner, `pill` a button or chip. */
  round?: "soft" | "pill";
}

export type Sketch = readonly SketchShape[];

/** The colour a role paints in the site's default theme. */
export function sketchColor(role: SketchRole): string {
  return themeColor(DOC, DEFAULT_THEME, SKETCH_ROLES[role]);
}

function attr(value: number): string {
  // Trailing zeroes in an SVG attribute are bytes in every block config the
  // panel downloads, and the grid only ever produces halves and quarters.
  return String(Math.round(value * 100) / 100);
}

/** Validation, because a shape off the grid renders as nothing at all and
 *  an empty tile looks exactly like a section that forgot to declare one. */
function assertOnGrid(shape: SketchShape, index: number): void {
  const { x, y, w, h } = shape;
  const bad =
    !Number.isFinite(x) ||
    !Number.isFinite(y) ||
    !(w > 0) ||
    !(h > 0) ||
    x < 0 ||
    y < 0 ||
    x + w > SKETCH_GRID.columns ||
    y + h > SKETCH_GRID.rows;
  if (bad) {
    throw new Error(
      `Sketch shape ${String(index)} (${shape.role}) is off the ${String(SKETCH_GRID.columns)}x${String(SKETCH_GRID.rows)} grid: ` +
        `x=${String(x)} y=${String(y)} w=${String(w)} h=${String(h)}`,
    );
  }
}

/** The SVG source of a sketch. Deterministic: same sketch, same bytes. */
export function sketchSvg(sketch: Sketch): string {
  if (sketch.length === 0) throw new Error("A section thumbnail needs at least one shape");
  const { width, height } = THUMBNAIL_SIZE;
  const body = sketch
    .map((shape, index) => {
      assertOnGrid(shape, index);
      const w = shape.w * UNIT;
      const h = shape.h * UNIT;
      const radius = shape.round === "pill" ? h / 2 : shape.round === "soft" ? 6 : 0;
      const rx = radius === 0 ? "" : ` rx="${attr(radius)}"`;
      return (
        `<rect x="${attr(shape.x * UNIT)}" y="${attr(shape.y * UNIT)}" ` +
        `width="${attr(w)}" height="${attr(h)}"${rx} fill="${sketchColor(shape.role)}"/>`
      );
    })
    .join("");
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${String(width)}" height="${String(height)}" ` +
    `viewBox="0 0 ${String(width)} ${String(height)}">` +
    `<rect width="${String(width)}" height="${String(height)}" fill="${themeColor(DOC, DEFAULT_THEME, "bg")}"/>` +
    `${body}</svg>`
  );
}

/**
 * The sketch as a `data:` URI, ready for `admin.images.thumbnail`.
 *
 * A data URI rather than a file under `public/`: the picture is derived from
 * the sketch on every boot, so a committed PNG would be a second copy that
 * can disagree with it, and the panel's CSP already allows `data:` for
 * images (apps/web/next.config.ts). Percent-encoded, not base64 — SVG is
 * text, and base64 would cost a third more bytes for nothing.
 */
export function sketchDataUri(sketch: Sketch): string {
  return `data:image/svg+xml,${encodeURIComponent(sketchSvg(sketch))}`;
}
