/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    redirects: Redirect;
    brands: Brand;
    categories: Category;
    products: Product;
    variants: Variant;
    prices: Price;
    inventory: Inventory;
    leads: Lead;
    orders: Order;
    payments: Payment;
    outbox: Outbox;
    returns: Return;
    carriers: Carrier;
    shipments: Shipment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    orders: {
      shipment: 'shipments';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    prices: PricesSelect<false> | PricesSelect<true>;
    inventory: InventorySelect<false> | InventorySelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    outbox: OutboxSelect<false> | OutboxSelect<true>;
    returns: ReturnsSelect<false> | ReturnsSelect<true>;
    carriers: CarriersSelect<false> | CarriersSelect<true>;
    shipments: ShipmentsSelect<false> | ShipmentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en' | 'ar') | ('es' | 'en' | 'ar')[];
  globals: {
    'theme-settings': ThemeSetting;
    'market-settings': MarketSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
    'market-settings': MarketSettingsSelect<false> | MarketSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: 'es' | 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cuentas del panel. Los clientes de la tienda no viven aquí.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Imágenes y vídeo. El alt es obligatorio y se traduce.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Lo que la imagen dice a quien no la ve. Es también el nombre con el que la mediateca lista este archivo.
   */
  alt: string;
  /**
   * Pie visible bajo la imagen en la galería de producto (opcional).
   */
  caption?: string | null;
  /**
   * Rol del asset en la galería canónica. El orden de PDP es: hero → detail/gallery → schematic → action; el resto es material interno o de secciones.
   */
  kind?:
    | (
        | 'hero'
        | 'gallery'
        | 'detail'
        | 'action'
        | 'lineup'
        | 'in-the-box'
        | 'service'
        | 'packaging'
        | 'schematic'
        | 'ecosystem'
        | 'contact-sheet'
      )
    | null;
  /**
   * Código de trazabilidad del evidence register (A-002…) o del board V0.4.
   */
  assetCode?: string | null;
  /**
   * concept = render CGI, se muestra SIEMPRE con etiqueta de render conceptual · blocked = jamás en PDP/campaña/RFQ (el storefront lo excluye aunque se adjunte) · published = fotografía real de muestra final.
   */
  evidenceStatus: 'concept' | 'blocked' | 'published';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Páginas componibles. El orden de las secciones es el orden en pantalla.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  blocks?:
    | (
        | {
            /**
             * Covers the whole band. Raise the scrim if the type over it stops being legible.
             */
            media?: (number | null) | Media;
            /**
             * Two or three words above the headline: “Launch”, “Padel”.
             */
            eyebrow?: string | null;
            /**
             * Second person, about the effect on the player rather than on the product.
             */
            heading: string;
            /**
             * Only one section per page may be the main headline.
             */
            level?: ('h2' | 'h1') | null;
            /**
             * One or two sentences. A figure with a unit convinces more than an adjective.
             */
            lead?: string | null;
            /**
             * The first is painted with the accent, the second stays quiet. Two at most.
             */
            ctas?:
              | {
                  label: string;
                  /**
                   * Region-relative path: /robots/tempo-r1.
                   */
                  href: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Under the buttons: “no payment, no commitment”, delivery window.
             */
            note?: string | null;
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Reserves screen for one moment of the page. Everything else keeps the vertical rhythm.
               */
              height?: ('auto' | 'tall' | 'full') | null;
              /**
               * Veils the media so type over it stays legible. The colour comes from the theme background.
               */
              overlay?: ('none' | 'soft' | 'strong' | 'gradient') | null;
              /**
               * Logical, not physical: it flips by itself in Arabic.
               */
              align?: ('start' | 'center') | null;
              /**
               * It measures the column, not the band: the background reaches the edge either way.
               */
              width?: ('prose' | 'content' | 'full') | null;
              /**
               * Transform only, never opacity: if the animation never runs, the section still shows.
               */
              reveal?: ('none' | 'rise' | 'settle') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'stage';
          }
        | {
            /**
             * Two or three words above the headline.
             */
            eyebrow?: string | null;
            /**
             * Second person, about the effect on the player.
             */
            heading: string;
            /**
             * Only one section per page may be the main headline.
             */
            level?: ('h2' | 'h1') | null;
            /**
             * One or two sentences. A figure with a unit convinces more than an adjective.
             */
            lead?: string | null;
            /**
             * The first is painted with the accent, the second stays quiet. Two at most.
             */
            ctas?:
              | {
                  label: string;
                  /**
                   * Region-relative path: /robots/tempo-r1.
                   */
                  href: string;
                  id?: string | null;
                }[]
              | null;
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Logical, not physical: it flips by itself in Arabic.
               */
              align?: ('start' | 'center') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Before the links: “On this page”. Empty = links only.
             */
            label?: string | null;
            /**
             * Between 2 and 8. An index of one is not an index.
             */
            items: {
              text: string;
              /**
               * The name you gave the target block, verbatim: the anchor is derived from it.
               */
              anchor: string;
              id?: string | null;
            }[];
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Hidden from everyone, screen readers included.
               */
              hiddenOn?: ('never' | 'mobile' | 'desktop') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'anchorNav';
          }
        | {
            /**
             * Prose with headings, lists and links. The column caps itself so it stays readable.
             */
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * It measures the column, not the band: the background reaches the edge either way.
               */
              width?: ('prose' | 'content' | 'full') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Takes half the band. The side is chosen under Design and flips by itself in Arabic.
             */
            image: number | Media;
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Logical, not physical: it swaps sides by itself in Arabic.
               */
              mediaPosition?: ('start' | 'end') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            heading?: string | null;
            /**
             * Between 2 and 8. Mix the sizes: a bento of equal tiles is just a grid.
             */
            items: {
              /**
               * On mobile every tile takes the full width.
               */
              span?: ('sm' | 'md' | 'lg') | null;
              image?: (number | null) | Media;
              eyebrow?: string | null;
              title: string;
              body?: string | null;
              id?: string | null;
            }[];
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Separates two bands that share a background, without inventing a colour.
               */
              divider?: ('none' | 'hairline' | 'soft') | null;
              /**
               * Transform only, never opacity: if the animation never runs, the section still shows.
               */
              reveal?: ('none' | 'rise' | 'settle') | null;
              /**
               * Hidden from everyone, screen readers included.
               */
              hiddenOn?: ('never' | 'mobile' | 'desktop') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'bento';
          }
        | {
            heading?: string | null;
            /**
             * Between 2 and 4. One figure is not a band; five do not get read.
             */
            items: {
              /**
               * With its unit: “72 km/h”, “140 balls”.
               */
              value: string;
              label: string;
              /**
               * “Measured on a sample”, “design target”. If it is not measured, it is not claimed.
               */
              note?: string | null;
              id?: string | null;
            }[];
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Logical, not physical: it flips by itself in Arabic.
               */
              align?: ('start' | 'center') | null;
              /**
               * Transform only, never opacity: if the animation never runs, the section still shows.
               */
              reveal?: ('none' | 'rise' | 'settle') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'statBand';
          }
        | {
            heading: string;
            /**
             * The column count is chosen under Design.
             */
            items?:
              | {
                  title: string;
                  /**
                   * Sport-specific: a padel ball bounces differently and the copy knows it.
                   */
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Always collapses to one column on mobile.
               */
              columns?: ('2' | '3' | '4') | null;
              /**
               * Logical, not physical: it flips by itself in Arabic.
               */
              align?: ('start' | 'center') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            heading?: string | null;
            lead?: string | null;
            /**
             * They number themselves in the order of this list. Between 2 and 6.
             */
            items: {
              title: string;
              body?: string | null;
              id?: string | null;
            }[];
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Always collapses to one column on mobile.
               */
              columns?: ('2' | '3' | '4') | null;
              /**
               * Separates two bands that share a background, without inventing a colour.
               */
              divider?: ('none' | 'hairline' | 'soft') | null;
              /**
               * Transform only, never opacity: if the animation never runs, the section still shows.
               */
              reveal?: ('none' | 'rise' | 'settle') | null;
              /**
               * Hidden from everyone, screen readers included.
               */
              hiddenOn?: ('never' | 'mobile' | 'desktop') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            heading?: string | null;
            lead?: string | null;
            /**
             * In chronological order, top to bottom. Between 2 and 6.
             */
            items: {
              /**
               * Short and in caps: “EVT”, “DVT”, “Pilot”.
               */
              label: string;
              title: string;
              body?: string | null;
              /**
               * Marks the dot on the rail. Only one should be in progress.
               */
              state?: ('done' | 'current' | 'next') | null;
              id?: string | null;
            }[];
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Transform only, never opacity: if the animation never runs, the section still shows.
               */
              reveal?: ('none' | 'rise' | 'settle') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            /**
             * The machine on a material or on-court background. The pins go on top of it.
             */
            image: number | Media;
            heading?: string | null;
            /**
             * Up to 8. Two pins on the same cell overlap.
             */
            points: {
              /**
               * A 12-column grid over the image; 1 is the starting edge.
               */
              col: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12';
              /**
               * An 8-row grid over the image; 1 is the top.
               */
              row: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8';
              title: string;
              body?: string | null;
              id?: string | null;
            }[];
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * It measures the column, not the band: the background reaches the edge either way.
               */
              width?: ('prose' | 'content' | 'full') | null;
              /**
               * Transform only, never opacity: if the animation never runs, the section still shows.
               */
              reveal?: ('none' | 'rise' | 'settle') | null;
              /**
               * Hidden from everyone, screen readers included.
               */
              hiddenOn?: ('never' | 'mobile' | 'desktop') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hotspots';
          }
        | {
            heading?: string | null;
            /**
             * Between 2 and 8. The column count is chosen under Design.
             */
            items: {
              image: number | Media;
              /**
               * Empty = the caption the image carries in the library is used.
               */
              caption?: string | null;
              id?: string | null;
            }[];
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Always collapses to one column on mobile.
               */
              columns?: ('2' | '3' | '4') | null;
              /**
               * Transform only, never opacity: if the animation never runs, the section still shows.
               */
              reveal?: ('none' | 'rise' | 'settle') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            /**
             * The block stores the reference only: price, currency and stock resolve live per market.
             */
            products: (number | Product)[];
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Logical, not physical: it flips by itself in Arabic.
               */
              align?: ('start' | 'center') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'productShowcase';
          }
        | {
            heading?: string | null;
            lead?: string | null;
            /**
             * Up to 4 columns. The figures and their state (measured, target) come from the catalogue, not from here.
             */
            products: (number | Product)[];
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Separates two bands that share a background, without inventing a colour.
               */
              divider?: ('none' | 'hairline' | 'soft') | null;
              /**
               * Transform only, never opacity: if the animation never runs, the section still shows.
               */
              reveal?: ('none' | 'rise' | 'settle') | null;
              /**
               * Hidden from everyone, screen readers included.
               */
              hiddenOn?: ('never' | 'mobile' | 'desktop') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'specTable';
          }
        | {
            provider: 'youtube' | 'vimeo';
            /**
             * The id only, not the URL: in youtube.com/watch?v=aqz-KESearI it is aqz-KESearI.
             */
            videoId: string;
            /**
             * Screen readers announce it. Say what is on screen, not “video”.
             */
            title: string;
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * It measures the column, not the band: the background reaches the edge either way.
               */
              width?: ('prose' | 'content' | 'full') | null;
              /**
               * Transform only, never opacity: if the animation never runs, the section still shows.
               */
              reveal?: ('none' | 'rise' | 'settle') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
        | {
            heading: string;
            /**
             * Say what happens after sending: when you reply and what they get.
             */
            body?: string | null;
            /**
             * It decides the fields, the confirmation email and how the lead enters the CRM.
             */
            intent: 'waitlist' | 'preorder' | 'demo';
            /**
             * Optional. If set, the lead is attached to that product.
             */
            product?: (number | Product)[] | null;
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Logical, not physical: it flips by itself in Arabic.
               */
              align?: ('start' | 'center') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'waitlist';
          }
        | {
            heading: string;
            /**
             * Up to 12. The ones that remove the fear of buying go first.
             */
            items?:
              | {
                  /**
                   * Written the way a customer would ask it, not the way marketing would title it.
                   */
                  question: string;
                  answer: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * It measures the column, not the band: the background reaches the edge either way.
               */
              width?: ('prose' | 'content' | 'full') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            /**
             * Their own words, without quote marks: the design adds those.
             */
            quote: string;
            author?: string | null;
            role?: string | null;
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Logical, not physical: it flips by itself in Arabic.
               */
              align?: ('start' | 'center') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            /**
             * One sentence asking for the next action, not a slogan.
             */
            heading: string;
            body?: string | null;
            /**
             * One only, on purpose: a band with two exits closes neither.
             */
            cta?:
              | {
                  label: string;
                  /**
                   * Region-relative path: /robots/tempo-r1.
                   */
                  href: string;
                  id?: string | null;
                }[]
              | null;
            appearance?: {
              /**
               * Air between this section and the one above, on the brand scale.
               */
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * Air between this section and the next, on the brand scale.
               */
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              /**
               * A theme role, never a colour. Inverted and accent rebind the text so contrast holds.
               */
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              /**
               * Logical, not physical: it flips by itself in Arabic.
               */
              align?: ('start' | 'center') | null;
              /**
               * Nests one brand theme inside this section only; the rest of the page is untouched.
               */
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBand';
          }
      )[]
    | null;
  seo?: {
    /**
     * Solo si el título de buscador debe diferir del de la página. Google corta sobre los 60 caracteres.
     */
    title?: string | null;
    /**
     * Lo que se lee bajo el enlace en Google y al compartir. Una frase concreta; sin “Descubre” ni adjetivos sin medida.
     */
    description?: string | null;
    /**
     * Imagen al compartir (1200×630). Sin ella se genera una tarjeta con el título y los colores del tema activo.
     */
    ogImage?: (number | null) | Media;
    /**
     * La página sigue siendo pública y navegable; solo se le pide a los buscadores que no la listen. Se suma al noindex de la región: una región no publicada no se reactiva desmarcando esto.
     */
    noIndex?: boolean | null;
  };
  /**
   * kebab-case, sin barras: forma la URL /{región}/{slug}. No se traduce.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * La familia (Drill Pro, Drill One…). La configuración por deporte vive en sus variantes (ADR-04).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Forma la URL /{región}/robots/{slug}. No se traduce.
   */
  slug: string;
  /**
   * Faceta de listado. La variante concreta fija SU deporte.
   */
  sports: ('tenis' | 'padel' | 'pickleball')[];
  category?: (number | null) | Category;
  /**
   * Marca de la casa bajo la que se vende (Drill, Gear…).
   */
  brand?: (number | null) | Brand;
  /**
   * available = a la venta · preorder = preventa con precio · waitlist = sin precio, captura lista de espera (lanzamiento estilo Kickstarter = waitlist + una landing del CMS).
   */
  launchStatus: 'available' | 'preorder' | 'waitlist';
  /**
   * Producto sobre material (aluminio/carbono) o pista real — nunca stock genérico (guía de marca). La primera es la principal.
   */
  images?: (number | Media)[] | null;
  excerpt?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * key técnica estable (velocidad, capacidad…) para alinear el comparador; el valor sí se traduce.
   */
  specs?:
    | {
        /**
         * Identificador estable para alinear el comparador. No se muestra.
         */
        key: string;
        /**
         * Etiqueta visible de la fila (Capacidad, Velocidad…).
         */
        label: string;
        value: string;
        unit?: string | null;
        /**
         * Estado de verificación (register CV-DATA): target = objetivo de diseño · factory_claim = dato OEM sin verificar · sample_tested/pilot_verified = medido · published = verificado y aprobado. La PDP etiqueta todo lo no-published.
         */
        evidence: 'target' | 'factory_claim' | 'sample_tested' | 'pilot_verified' | 'published';
        id?: string | null;
      }[]
    | null;
  warrantyMonths?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Facetas de catálogo: robots, palas, bolas…
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  sport?: ('tenis' | 'padel' | 'pickleball') | null;
  /**
   * Cabecera de la página de categoría. Material o pista, nunca stock.
   */
  image?: (number | null) | Media;
  /**
   * Se muestra bajo el título en /{región}/c/{slug}.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Marcas de la casa (Drill, Gear…). Multimarca sin multi-sitio: una faceta, no un fork.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Rutas relativas a la región (/tecnologia, no /es/tecnologia): una fila cubre es, en-gb, en-ae y ar-ae. Al renombrar el slug de una página se crea sola.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * URL antigua, sin el prefijo de región. Ej.: /tecnologia
   */
  from: string;
  /**
   * URL nueva, sin el prefijo de región. Ej.: /tecnologia-tempo
   */
  to: string;
  /**
   * 301 para un cambio definitivo de URL. 302 solo mientras algo esté de paso: un 302 no traslada el posicionamiento.
   */
  code: '301' | '302';
  /**
   * Quién creó la fila. Las automáticas se reescriben solas al volver a renombrar.
   */
  source: 'manual' | 'slug-change';
  updatedAt: string;
  createdAt: string;
}
/**
 * Un SKU por deporte y configuración (Drill Pro → T / P / PB).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  product: number | Product;
  sku: string;
  sport: 'tenis' | 'padel' | 'pickleball';
  attributes?:
    | {
        name: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  weightKg?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SOLO SERVIDOR. Importes en unidades menores (129000 = 1.290,00). La moneda la fija el mercado en código: nunca hay conversión en runtime (ADR-05).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prices".
 */
export interface Price {
  id: number;
  variant: number | Variant;
  /**
   * De la variante enlazada. No es una columna: renombrar el SKU lo cambia aquí también.
   */
  sku?: string | null;
  market: 'es' | 'uk' | 'ae';
  amount: number;
  /**
   * Precio anterior tachado, mismas unidades menores que amount.
   */
  compareAtAmount?: number | null;
  taxBehavior: 'inclusive' | 'exclusive';
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SOLO SERVIDOR. Disponible = en mano − comprometido; se compromete solo tras `paid`.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory".
 */
export interface Inventory {
  id: number;
  variant: number | Variant;
  /**
   * De la variante enlazada. No es una columna: renombrar el SKU lo cambia aquí también.
   */
  sku?: string | null;
  qtyOnHand: number;
  qtyCommitted: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Captación comercial. Se crean desde el formulario web (server action), nunca por REST público.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  market: 'es' | 'uk' | 'ae';
  sportInterest?: ('tenis' | 'padel' | 'pickleball') | null;
  /**
   * Qué pedía el visitante: demo, lista de espera o reserva (preventa).
   */
  intent: 'demo' | 'waitlist' | 'preorder';
  product?: (number | null) | Product;
  /**
   * Configuración que el comprador marcó en el formulario (si eligió una).
   */
  variantSku?: string | null;
  message?: string | null;
  consent: boolean;
  /**
   * El texto exacto de consentimiento que se mostró al enviar (RGPD art. 7.1: el consentimiento debe poder demostrarse).
   */
  consentText?: string | null;
  /**
   * Pipeline mínimo: nuevo → contactado → cerrado.
   */
  status: 'new' | 'contacted' | 'closed';
  locale?: string | null;
  sourcePath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SOLO SERVIDOR. El estado lo mueve la máquina de estados dentro de una transacción — nunca se edita a mano (docs/orders-state-machine.md).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Lo mueve la máquina de estados: pagos por webhook, envíos desde la colección Envíos. No se edita.
   */
  status:
    | 'draft'
    | 'pending_payment'
    | 'paid'
    | 'cancelled'
    | 'preparing'
    | 'shipped'
    | 'delivered'
    | 'refund_requested'
    | 'refund_failed'
    | 'refunded'
    | 'partially_refunded'
    | 'return_requested'
    | 'return_received';
  market: 'es' | 'uk' | 'ae';
  email: string;
  locale?: string | null;
  lines: {
    variant: number | Variant;
    sku: string;
    quantity: number;
    /**
     * Unidades menores, copiadas del precio del mercado al crear.
     */
    unitAmount: number;
    id?: string | null;
  }[];
  totalAmount: number;
  /**
   * 0 mientras los precios son inclusive; el motor fiscal llega con la pasarela.
   */
  taxAmount: number;
  refundedAmount: number;
  shippingAddress: {
    name: string;
    line1: string;
    line2?: string | null;
    city: string;
    postalCode: string;
    country: string;
  };
  billingAddress?: {
    name?: string | null;
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  /**
   * Pasarela elegida por el cliente (ADR-14).
   */
  provider?: ('stripe' | 'tabby' | 'tamara' | 'adyen') | null;
  /**
   * Id del pago en la pasarela; llega al crear la sesión.
   */
  providerPaymentId?: string | null;
  /**
   * El envío de este pedido, si ya se abrió.
   */
  shipment?: {
    docs?: (number | Shipment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * El envío ES la transición: crearlo manda el pedido a preparar, rellenar transportista y seguimiento lo marca enviado, y fechar la entrega lo cierra. Si la máquina de estados no lo permite, no se guarda.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipments".
 */
export interface Shipment {
  id: number;
  /**
   * Un envío por pedido: la máquina rechaza el segundo, porque `shipped` es un único estado.
   */
  order: number | Order;
  /**
   * Al rellenarlo junto con el número de seguimiento, el pedido pasa a enviado.
   */
  carrier?: (number | null) | Carrier;
  /**
   * Número que da el transportista. Va tal cual en el email al cliente.
   */
  trackingNumber?: string | null;
  /**
   * Se construye con la plantilla del transportista; no se escribe a mano.
   */
  trackingUrl?: string | null;
  /**
   * La pone la transición al marcar enviado.
   */
  shippedAt?: string | null;
  /**
   * Fecharla cierra el pedido como entregado y abre el desistimiento.
   */
  deliveredAt?: string | null;
  /**
   * Del mercado del pedido (ADR-08: EAU se sirve DDP vía courier-broker).
   */
  incoterm?: ('DDP' | 'DDU') | null;
  /**
   * Quién movió el envío por última vez. Un envío lo marca una persona, no un webhook.
   */
  markedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Añadir un transportista es crear una fila, no un despliegue: la URL de seguimiento es una plantilla, no código.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carriers".
 */
export interface Carrier {
  id: number;
  /**
   * Identificador estable en minúsculas: seur, dpd, aramex.
   */
  code: string;
  /**
   * Nombre visible para quien prepara el envío.
   */
  name: string;
  /**
   * URL de seguimiento con {tracking} donde va el número. Ej.: https://track.aramex.com/{tracking}
   */
  trackingUrlTemplate: string;
  /**
   * Mercados en los que se puede usar. Vacío = todos. Un pedido de otro mercado se rechaza al guardar el envío.
   */
  markets?: ('es' | 'uk' | 'ae')[] | null;
  /**
   * Desmarcar retira el transportista sin borrar los envíos que lo usaron.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SOLO SERVIDOR. Libro de eventos de pago normalizados. La fila se inserta ANTES de la transición: (provider, providerEventId) UNIQUE es la idempotencia — un webhook repetido revienta aquí, sin efectos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  provider: 'stripe' | 'tabby' | 'tamara' | 'adyen';
  providerEventId: string;
  type: 'authorized' | 'paid' | 'failed' | 'refunded' | 'refund_failed';
  order: number | Order;
  providerPaymentId?: string | null;
  amount: number;
  partial?: boolean | null;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * SOLO SERVIDOR. Efectos externos (email, factura, reembolso en pasarela) escritos en la MISMA transacción que la transición y despachados después del commit — un rollback no des-envía un email.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outbox".
 */
export interface Outbox {
  id: number;
  effect:
    | 'restock_if_applicable'
    | 'start_picking'
    | 'stop_picking'
    | 'send_confirmation_email'
    | 'notify_crm'
    | 'issue_tax_invoice'
    | 'send_tracking_email'
    | 'send_post_sale_email'
    | 'open_withdrawal_window'
    | 'execute_provider_refund'
    | 'send_refund_email'
    | 'issue_credit_note'
    | 'alert_refund_failure'
    | 'alert_payment_conflict'
    | 'notify_sales_lead';
  order?: (number | null) | Order;
  lead?: (number | null) | Lead;
  status: 'pending' | 'dispatched' | 'failed';
  /**
   * Datos del efecto (p. ej. importe de un reembolso, en unidades menores).
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  attempts: number;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SOLO SERVIDOR. RMA: la aprobación humana del reembolso (refund.approved) es el ÚNICO disparador que ordena ejecutar un reembolso en la pasarela.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns".
 */
export interface Return {
  id: number;
  order: number | Order;
  /**
   * Del pedido enlazado. No es una columna.
   */
  customer?: string | null;
  status: 'requested' | 'received' | 'refunded' | 'rejected';
  lines: {
    sku: string;
    quantity: number;
    id?: string | null;
  }[];
  reason: string;
  refundAmount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'prices';
        value: number | Price;
      } | null)
    | ({
        relationTo: 'inventory';
        value: number | Inventory;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'outbox';
        value: number | Outbox;
      } | null)
    | ({
        relationTo: 'returns';
        value: number | Return;
      } | null)
    | ({
        relationTo: 'carriers';
        value: number | Carrier;
      } | null)
    | ({
        relationTo: 'shipments';
        value: number | Shipment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  kind?: T;
  assetCode?: T;
  evidenceStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  blocks?:
    | T
    | {
        stage?:
          | T
          | {
              media?: T;
              eyebrow?: T;
              heading?: T;
              level?: T;
              lead?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              note?: T;
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    height?: T;
                    overlay?: T;
                    align?: T;
                    width?: T;
                    reveal?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              level?: T;
              lead?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    align?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        anchorNav?:
          | T
          | {
              label?: T;
              items?:
                | T
                | {
                    text?: T;
                    anchor?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    hiddenOn?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              body?: T;
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    width?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              image?: T;
              heading?: T;
              body?: T;
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    mediaPosition?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bento?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    span?: T;
                    image?: T;
                    eyebrow?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    divider?: T;
                    reveal?: T;
                    hiddenOn?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statBand?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    note?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    align?: T;
                    reveal?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    columns?: T;
                    align?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              heading?: T;
              lead?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    columns?: T;
                    divider?: T;
                    reveal?: T;
                    hiddenOn?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              heading?: T;
              lead?: T;
              items?:
                | T
                | {
                    label?: T;
                    title?: T;
                    body?: T;
                    state?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    reveal?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hotspots?:
          | T
          | {
              image?: T;
              heading?: T;
              points?:
                | T
                | {
                    col?: T;
                    row?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    width?: T;
                    reveal?: T;
                    hiddenOn?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    columns?: T;
                    reveal?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productShowcase?:
          | T
          | {
              heading?: T;
              products?: T;
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    align?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        specTable?:
          | T
          | {
              heading?: T;
              lead?: T;
              products?: T;
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    divider?: T;
                    reveal?: T;
                    hiddenOn?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              provider?: T;
              videoId?: T;
              title?: T;
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    width?: T;
                    reveal?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        waitlist?:
          | T
          | {
              heading?: T;
              body?: T;
              intent?: T;
              product?: T;
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    align?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    width?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              author?: T;
              role?: T;
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    align?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBand?:
          | T
          | {
              heading?: T;
              body?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    align?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  code?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sport?: T;
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sports?: T;
  category?: T;
  brand?: T;
  launchStatus?: T;
  images?: T;
  excerpt?: T;
  description?: T;
  specs?:
    | T
    | {
        key?: T;
        label?: T;
        value?: T;
        unit?: T;
        evidence?: T;
        id?: T;
      };
  warrantyMonths?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  product?: T;
  sku?: T;
  sport?: T;
  attributes?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  weightKg?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prices_select".
 */
export interface PricesSelect<T extends boolean = true> {
  variant?: T;
  sku?: T;
  market?: T;
  amount?: T;
  compareAtAmount?: T;
  taxBehavior?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory_select".
 */
export interface InventorySelect<T extends boolean = true> {
  variant?: T;
  sku?: T;
  qtyOnHand?: T;
  qtyCommitted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  market?: T;
  sportInterest?: T;
  intent?: T;
  product?: T;
  variantSku?: T;
  message?: T;
  consent?: T;
  consentText?: T;
  status?: T;
  locale?: T;
  sourcePath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  status?: T;
  market?: T;
  email?: T;
  locale?: T;
  lines?:
    | T
    | {
        variant?: T;
        sku?: T;
        quantity?: T;
        unitAmount?: T;
        id?: T;
      };
  totalAmount?: T;
  taxAmount?: T;
  refundedAmount?: T;
  shippingAddress?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  billingAddress?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  provider?: T;
  providerPaymentId?: T;
  shipment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  provider?: T;
  providerEventId?: T;
  type?: T;
  order?: T;
  providerPaymentId?: T;
  amount?: T;
  partial?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outbox_select".
 */
export interface OutboxSelect<T extends boolean = true> {
  effect?: T;
  order?: T;
  lead?: T;
  status?: T;
  payload?: T;
  attempts?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns_select".
 */
export interface ReturnsSelect<T extends boolean = true> {
  order?: T;
  customer?: T;
  status?: T;
  lines?:
    | T
    | {
        sku?: T;
        quantity?: T;
        id?: T;
      };
  reason?: T;
  refundAmount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carriers_select".
 */
export interface CarriersSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  trackingUrlTemplate?: T;
  markets?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipments_select".
 */
export interface ShipmentsSelect<T extends boolean = true> {
  order?: T;
  carrier?: T;
  trackingNumber?: T;
  trackingUrl?: T;
  shippedAt?: T;
  deliveredAt?: T;
  incoterm?: T;
  markedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Abre «Vista previa» para ver el sitio con lo ÚLTIMO GUARDADO: estos ajustes no tienen borrador, se publican al guardar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: number;
  /**
   * Re-viste el sitio entero al publicar. Las páginas y secciones pueden declarar su propio tema por encima.
   */
  activeTheme: 'volt' | 'carbon' | 'club';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Qué pasarelas ofrece cada mercado y en qué orden. La moneda y el incoterm NO están aquí: son código (@courvia/platform).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-settings".
 */
export interface MarketSetting {
  id: number;
  /**
   * Un elemento por mercado activo. ES · UK · AE.
   */
  markets?:
    | {
        market: 'es' | 'uk' | 'ae';
        /**
         * Desmarcado = el checkout no ofrece este mercado.
         */
        enabled?: boolean | null;
        /**
         * Orden de presentación en el checkout; el cliente elige.
         */
        paymentProviders?:
          | {
              provider: 'stripe' | 'tabby' | 'tamara' | 'adyen';
              enabled?: boolean | null;
              /**
               * Métodos que este proveedor ofrece en este mercado (Bizum y Klarna van DENTRO de Stripe). Vacío = los que la pasarela active por defecto.
               */
              methods?: ('card' | 'bizum' | 'klarna' | 'sequra' | 'clearpay' | 'apple_pay' | 'google_pay')[] | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Menú de cabecera y enlaces de pie. Rutas relativas a la región. «Vista previa» abre el sitio con lo último guardado: este global no tiene borrador.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Enlaces del menú principal, en orden.
   */
  header?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Botón destacado a la derecha del menú (p. ej. «Pide una demo»). Sin label no se muestra.
   */
  headerCta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Columnas del pie con título (Comprar · Empresa · Ayuda…). El canon de las tiendas serias: 3-5 columnas por intención del visitante.
   */
  footerGroups?:
    | {
        label: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Fila inferior del pie (legales), junto al copyright y el selector de región.
   */
  footer?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  activeTheme?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-settings_select".
 */
export interface MarketSettingsSelect<T extends boolean = true> {
  markets?:
    | T
    | {
        market?: T;
        enabled?: T;
        paymentProviders?:
          | T
          | {
              provider?: T;
              enabled?: T;
              methods?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  footerGroups?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}