/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    categories: Category;
    products: Product;
    variants: Variant;
    prices: Price;
    inventory: Inventory;
    leads: Lead;
    orders: Order;
    payments: Payment;
    outbox: Outbox;
    returns: Return;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    prices: PricesSelect<false> | PricesSelect<true>;
    inventory: InventorySelect<false> | InventorySelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    outbox: OutboxSelect<false> | OutboxSelect<true>;
    returns: ReturnsSelect<false> | ReturnsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en' | 'ar') | ('es' | 'en' | 'ar')[];
  globals: {
    'theme-settings': ThemeSetting;
    'market-settings': MarketSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
    'market-settings': MarketSettingsSelect<false> | MarketSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: 'es' | 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cuentas del panel. Los clientes de la tienda no viven aquí.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Imágenes y vídeo. El alt es obligatorio y se traduce.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Páginas componibles. El orden de las secciones es el orden en pantalla.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * kebab-case, sin barras: forma la URL /{región}/{slug}. No se traduce.
   */
  slug: string;
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            lead?: string | null;
            ctas?:
              | {
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Controles ligados a los tokens de marca. No hay valores libres: el sistema garantiza contraste y coherencia.
             */
            appearance?: {
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              align?: ('start' | 'center') | null;
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Controles ligados a los tokens de marca. No hay valores libres: el sistema garantiza contraste y coherencia.
             */
            appearance?: {
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              width?: ('prose' | 'content' | 'full') | null;
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading: string;
            body?: string | null;
            cta?:
              | {
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Controles ligados a los tokens de marca. No hay valores libres: el sistema garantiza contraste y coherencia.
             */
            appearance?: {
              spaceBlockStart?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              spaceBlockEnd?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
              background?: ('none' | 'surface' | 'raised' | 'inverse' | 'accent') | null;
              align?: ('start' | 'center') | null;
              themeScope?: ('inherit' | 'volt' | 'carbon' | 'club') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBand';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Facetas de catálogo: robots, palas, bolas…
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  sport?: ('tenis' | 'padel' | 'pickleball') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * La familia (Drill Pro, Drill One…). La configuración por deporte vive en sus variantes (ADR-04).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Forma la URL /{región}/robots/{slug}. No se traduce.
   */
  slug: string;
  /**
   * Faceta de listado. La variante concreta fija SU deporte.
   */
  sports: ('tenis' | 'padel' | 'pickleball')[];
  category?: (number | null) | Category;
  /**
   * Producto sobre material (aluminio/carbono) o pista real — nunca stock genérico (guía de marca). La primera es la principal.
   */
  images?: (number | Media)[] | null;
  excerpt?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * key técnica estable (velocidad, capacidad…) para alinear el comparador; el valor sí se traduce.
   */
  specs?:
    | {
        /**
         * Identificador estable para alinear el comparador. No se muestra.
         */
        key: string;
        /**
         * Etiqueta visible de la fila (Capacidad, Velocidad…).
         */
        label: string;
        value: string;
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  warrantyMonths?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Un SKU por deporte y configuración (Drill Pro → T / P / PB).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  product: number | Product;
  sku: string;
  sport: 'tenis' | 'padel' | 'pickleball';
  attributes?:
    | {
        name: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  weightKg?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SOLO SERVIDOR. Importes en unidades menores (129000 = 1.290,00). La moneda la fija el mercado en código: nunca hay conversión en runtime (ADR-05).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prices".
 */
export interface Price {
  id: number;
  variant: number | Variant;
  market: 'es' | 'uk' | 'ae';
  amount: number;
  /**
   * Precio anterior tachado, mismas unidades menores que amount.
   */
  compareAtAmount?: number | null;
  taxBehavior: 'inclusive' | 'exclusive';
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SOLO SERVIDOR. Disponible = en mano − comprometido; se compromete solo tras `paid`.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory".
 */
export interface Inventory {
  id: number;
  variant: number | Variant;
  qtyOnHand: number;
  qtyCommitted: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Captación comercial. Se crean desde el formulario web (server action), nunca por REST público.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  market: 'es' | 'uk' | 'ae';
  sportInterest?: ('tenis' | 'padel' | 'pickleball') | null;
  product?: (number | null) | Product;
  /**
   * Configuración que el comprador marcó en el formulario (si eligió una).
   */
  variantSku?: string | null;
  message?: string | null;
  consent: boolean;
  /**
   * El texto exacto de consentimiento que se mostró al enviar (RGPD art. 7.1: el consentimiento debe poder demostrarse).
   */
  consentText?: string | null;
  /**
   * Pipeline mínimo: nuevo → contactado → cerrado.
   */
  status: 'new' | 'contacted' | 'closed';
  locale?: string | null;
  sourcePath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SOLO SERVIDOR. El estado lo mueve la máquina de estados dentro de una transacción — nunca se edita a mano (docs/orders-state-machine.md).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Solo lo mueve la máquina de estados. No editar.
   */
  status:
    | 'draft'
    | 'pending_payment'
    | 'paid'
    | 'cancelled'
    | 'preparing'
    | 'shipped'
    | 'delivered'
    | 'refund_requested'
    | 'refund_failed'
    | 'refunded'
    | 'partially_refunded'
    | 'return_requested'
    | 'return_received';
  market: 'es' | 'uk' | 'ae';
  email: string;
  locale?: string | null;
  lines: {
    variant: number | Variant;
    sku: string;
    quantity: number;
    /**
     * Unidades menores, copiadas del precio del mercado al crear.
     */
    unitAmount: number;
    id?: string | null;
  }[];
  totalAmount: number;
  /**
   * 0 mientras los precios son inclusive; el motor fiscal llega con la pasarela.
   */
  taxAmount: number;
  refundedAmount: number;
  shippingAddress: {
    name: string;
    line1: string;
    line2?: string | null;
    city: string;
    postalCode: string;
    country: string;
  };
  billingAddress?: {
    name?: string | null;
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  /**
   * Pasarela elegida por el cliente (ADR-14).
   */
  provider?: ('stripe' | 'tabby' | 'tamara' | 'adyen') | null;
  /**
   * Id del pago en la pasarela; llega al crear la sesión.
   */
  providerPaymentId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SOLO SERVIDOR. Libro de eventos de pago normalizados. La fila se inserta ANTES de la transición: (provider, providerEventId) UNIQUE es la idempotencia — un webhook repetido revienta aquí, sin efectos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  provider: 'stripe' | 'tabby' | 'tamara' | 'adyen';
  providerEventId: string;
  type: 'authorized' | 'paid' | 'failed' | 'refunded' | 'refund_failed';
  order: number | Order;
  providerPaymentId?: string | null;
  amount: number;
  partial?: boolean | null;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * SOLO SERVIDOR. Efectos externos (email, factura, reembolso en pasarela) escritos en la MISMA transacción que la transición y despachados después del commit — un rollback no des-envía un email.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outbox".
 */
export interface Outbox {
  id: number;
  effect:
    | 'restock_if_applicable'
    | 'send_confirmation_email'
    | 'notify_crm'
    | 'issue_tax_invoice'
    | 'send_tracking_email'
    | 'send_post_sale_email'
    | 'open_withdrawal_window'
    | 'execute_provider_refund'
    | 'send_refund_email'
    | 'issue_credit_note'
    | 'alert_refund_failure'
    | 'alert_payment_conflict'
    | 'notify_sales_lead';
  order?: (number | null) | Order;
  lead?: (number | null) | Lead;
  status: 'pending' | 'dispatched' | 'failed';
  /**
   * Datos del efecto (p. ej. importe de un reembolso, en unidades menores).
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  attempts: number;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SOLO SERVIDOR. RMA: la aprobación humana del reembolso (refund.approved) es el ÚNICO disparador que ordena ejecutar un reembolso en la pasarela.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns".
 */
export interface Return {
  id: number;
  order: number | Order;
  status: 'requested' | 'received' | 'refunded' | 'rejected';
  lines: {
    sku: string;
    quantity: number;
    id?: string | null;
  }[];
  reason: string;
  refundAmount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'prices';
        value: number | Price;
      } | null)
    | ({
        relationTo: 'inventory';
        value: number | Inventory;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'outbox';
        value: number | Outbox;
      } | null)
    | ({
        relationTo: 'returns';
        value: number | Return;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              lead?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    align?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              body?: T;
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    width?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBand?:
          | T
          | {
              heading?: T;
              body?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    spaceBlockStart?: T;
                    spaceBlockEnd?: T;
                    background?: T;
                    align?: T;
                    themeScope?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sports?: T;
  category?: T;
  images?: T;
  excerpt?: T;
  description?: T;
  specs?:
    | T
    | {
        key?: T;
        label?: T;
        value?: T;
        unit?: T;
        id?: T;
      };
  warrantyMonths?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  product?: T;
  sku?: T;
  sport?: T;
  attributes?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  weightKg?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prices_select".
 */
export interface PricesSelect<T extends boolean = true> {
  variant?: T;
  market?: T;
  amount?: T;
  compareAtAmount?: T;
  taxBehavior?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory_select".
 */
export interface InventorySelect<T extends boolean = true> {
  variant?: T;
  qtyOnHand?: T;
  qtyCommitted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  market?: T;
  sportInterest?: T;
  product?: T;
  variantSku?: T;
  message?: T;
  consent?: T;
  consentText?: T;
  status?: T;
  locale?: T;
  sourcePath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  status?: T;
  market?: T;
  email?: T;
  locale?: T;
  lines?:
    | T
    | {
        variant?: T;
        sku?: T;
        quantity?: T;
        unitAmount?: T;
        id?: T;
      };
  totalAmount?: T;
  taxAmount?: T;
  refundedAmount?: T;
  shippingAddress?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  billingAddress?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  provider?: T;
  providerPaymentId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  provider?: T;
  providerEventId?: T;
  type?: T;
  order?: T;
  providerPaymentId?: T;
  amount?: T;
  partial?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outbox_select".
 */
export interface OutboxSelect<T extends boolean = true> {
  effect?: T;
  order?: T;
  lead?: T;
  status?: T;
  payload?: T;
  attempts?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns_select".
 */
export interface ReturnsSelect<T extends boolean = true> {
  order?: T;
  status?: T;
  lines?:
    | T
    | {
        sku?: T;
        quantity?: T;
        id?: T;
      };
  reason?: T;
  refundAmount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: number;
  /**
   * Re-viste el sitio entero al publicar. Las páginas y secciones pueden declarar su propio tema por encima.
   */
  activeTheme: 'volt' | 'carbon' | 'club';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-settings".
 */
export interface MarketSetting {
  id: number;
  /**
   * Un elemento por mercado activo. ES · UK · AE.
   */
  markets?:
    | {
        market: 'es' | 'uk' | 'ae';
        enabled?: boolean | null;
        /**
         * Orden de presentación en el checkout; el cliente elige.
         */
        paymentProviders?:
          | {
              provider: 'stripe' | 'tabby' | 'tamara' | 'adyen';
              enabled?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Menú de cabecera y enlaces de pie. Rutas relativas a la región.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Enlaces del menú principal, en orden.
   */
  header?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Enlaces del pie (legales, contacto…), en orden.
   */
  footer?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  activeTheme?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-settings_select".
 */
export interface MarketSettingsSelect<T extends boolean = true> {
  markets?:
    | T
    | {
        market?: T;
        enabled?: T;
        paymentProviders?:
          | T
          | {
              provider?: T;
              enabled?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}