/**
 * Generates dist/appearance.css from the SAME table the resolver uses, so
 * the enum vocabulary and the stylesheet cannot drift — a coverage test
 * asserts the bijection.
 */
import { CONTROLS, CONTROL_NAMES, SECTION_INNER_CLASS } from "./controls";
import type { ControlDefinition } from "./controls";

export function buildAppearanceCss(): string {
  // The DEFAULT of every control lives in the BASE wrapper rule: the
  // resolver deliberately emits no attribute for a default value (quiet
  // DOM), so without this a section with default appearance would render
  // with NO rhythm at all. Attribute rules share the base rule's
  // specificity and come later, so any non-default value still wins.
  const defaultDeclarations = CONTROL_NAMES.map((name) => {
    const control: ControlDefinition = CONTROLS[name];
    return control.css?.[control.default] ?? "";
  })
    .filter((declarations) => declarations !== "")
    .join(" ");

  const blocks: string[] = [
    "/* Generated by @courvia/appearance — do not edit by hand. */",
    // TWO elements, because one cannot do both jobs. The BAND paints
    // (background, divider, block rhythm, band height) and therefore has no
    // inline size of its own: it is as wide as whatever contains it, which
    // is what lets `background: surface` run edge to edge instead of
    // floating as a rectangle with the page background either side. The
    // INNER measures (measure + inline padding) and centres itself in the
    // band. Webflow calls the pair Section/Container, Dawn `<section>` +
    // `.page-width`, theme.json contentSize inside a `full` group; the
    // footer of this very app already does it (.site-footer /
    // .site-footer-inner). Merge them again and "wide band, narrow column"
    // stops existing.
    //
    // `color` stays on the BAND, not the inner: an inherited color is a
    // computed value frozen at the body, so a background's --cv-color-text
    // rebind (inverse/accent) would never reach headings that don't declare
    // their own color. The rebind happens on the band — resolving the var
    // there makes it apply to the whole subtree by construction.
    //
    // The defaults ride along on the band because every one of them is
    // either a custom property or an inherited property (text-align), so
    // the inner receives them without a second rule.
    `[data-cv-section] { color: var(--cv-color-text); ${defaultDeclarations} }`,
    `[data-cv-section] > .${SECTION_INNER_CLASS} { inline-size: 100%; margin-inline: auto; max-inline-size: var(--cv-section-measure, var(--cv-breakpoint-xl)); padding-inline: var(--cv-space-6); }`,
  ];
  for (const name of CONTROL_NAMES) {
    const control: ControlDefinition = CONTROLS[name];
    if (control.css === null) continue;
    for (const value of control.values) {
      const declarations = control.css[value];
      if (declarations === undefined || declarations === "") continue;
      blocks.push(`[${control.attribute}='${value}'] { ${declarations} }`);
    }
  }
  return blocks.join("\n") + "\n";
}

/* CLI entry: tsx src/build-css.ts */
if (
  process.argv[1] !== undefined &&
  import.meta.url === (await import("node:url")).pathToFileURL(process.argv[1]).href
) {
  const { mkdir, writeFile } = await import("node:fs/promises");
  const { fileURLToPath } = await import("node:url");
  const { dirname, join } = await import("node:path");
  const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
  const css = buildAppearanceCss();
  await mkdir(join(pkgRoot, "dist"), { recursive: true });
  await writeFile(join(pkgRoot, "dist", "appearance.css"), css, "utf8");
  console.log(`appearance.css written (${css.length} bytes)`);
}
