/**
 * Generates dist/appearance.css from the SAME table the resolver uses, so
 * the enum vocabulary and the stylesheet cannot drift — a coverage test
 * asserts the bijection.
 */
import { CONTROLS, CONTROL_NAMES } from "./controls";
import type { ControlDefinition } from "./controls";

export function buildAppearanceCss(): string {
  // The DEFAULT of every control lives in the BASE wrapper rule: the
  // resolver deliberately emits no attribute for a default value (quiet
  // DOM), so without this a section with default appearance would render
  // with NO rhythm at all. Attribute rules share the base rule's
  // specificity and come later, so any non-default value still wins.
  const defaultDeclarations = CONTROL_NAMES.map((name) => {
    const control: ControlDefinition = CONTROLS[name];
    return control.css?.[control.default] ?? "";
  })
    .filter((declarations) => declarations !== "")
    .join(" ");

  const blocks: string[] = [
    "/* Generated by @courvia/appearance — do not edit by hand. */",
    // The wrapper every section gets; measure comes from the width control.
    // `color` is re-declared HERE, not inherited from body: an inherited
    // color is a computed value frozen at the body, so a background's
    // --cv-color-text rebind (inverse/accent) would never reach headings
    // that don't declare their own color. Resolving the var at the wrapper
    // makes every rebind apply to the whole subtree by construction.
    `[data-cv-section] { margin-inline: auto; inline-size: 100%; max-inline-size: var(--cv-section-measure, var(--cv-breakpoint-xl)); padding-inline: var(--cv-space-6); color: var(--cv-color-text); ${defaultDeclarations} }`,
  ];
  for (const name of CONTROL_NAMES) {
    const control: ControlDefinition = CONTROLS[name];
    if (control.css === null) continue;
    for (const value of control.values) {
      const declarations = control.css[value];
      if (declarations === undefined || declarations === "") continue;
      blocks.push(`[${control.attribute}='${value}'] { ${declarations} }`);
    }
  }
  return blocks.join("\n") + "\n";
}

/* CLI entry: tsx src/build-css.ts */
if (
  process.argv[1] !== undefined &&
  import.meta.url === (await import("node:url")).pathToFileURL(process.argv[1]).href
) {
  const { mkdir, writeFile } = await import("node:fs/promises");
  const { fileURLToPath } = await import("node:url");
  const { dirname, join } = await import("node:path");
  const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
  const css = buildAppearanceCss();
  await mkdir(join(pkgRoot, "dist"), { recursive: true });
  await writeFile(join(pkgRoot, "dist", "appearance.css"), css, "utf8");
  console.log(`appearance.css written (${css.length} bytes)`);
}
