import { sql } from '@payloadcms/db-postgres'
import type { MigrateDownArgs, MigrateUpArgs } from '@payloadcms/db-postgres'

/**
 * Fulfilment: `shipments`, `carriers` and the two warehouse effects.
 *
 * Generated by Payload, with three deliberate edits — each one is a bug the
 * generator cannot know about:
 *
 * 1. `shipments.order_id` is NOT NULL, and Payload's default FK action for a
 *    relationship is ON DELETE SET NULL. Postgres evaluates the SET NULL
 *    before the not-null check, so deleting an order that had a shipment
 *    would blow up with a raw 23502 (the same trap `variants.product_id`
 *    still carries). A shipment has no meaning without its order: CASCADE.
 * 2. RLS is enabled here explicitly instead of trusting the `ensure_rls`
 *    event trigger. The trigger needs superuser to exist at all, so on a
 *    restore, a Supabase branch or CI's throwaway Postgres these three
 *    tables could be born readable. `.claude/rules/database.md` is clear
 *    that a rule which only exists in one database is a coincidence.
 * 3. The migration asserts the end state — every table in `payload` with
 *    RLS on and not one policy — and raises if it is wrong.
 *
 * The two new `enum_outbox_effect` values are `start_picking` (reclassified
 * from transactional to outbox: telling the warehouse to pick is a message,
 * not a row of ours) and `stop_picking` (its counter-order when a refund is
 * requested mid-preparation).
 */

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "payload"."enum_carriers_markets" AS ENUM('es', 'uk', 'ae');
  CREATE TYPE "payload"."enum_shipments_incoterm" AS ENUM('DDP', 'DDU');
  ALTER TYPE "payload"."enum_outbox_effect" ADD VALUE 'start_picking' BEFORE 'send_confirmation_email';
  ALTER TYPE "payload"."enum_outbox_effect" ADD VALUE 'stop_picking' BEFORE 'send_confirmation_email';
  CREATE TABLE "payload"."carriers_markets" (
  	"order" integer NOT NULL,
  	"parent_id" integer NOT NULL,
  	"value" "payload"."enum_carriers_markets",
  	"id" serial PRIMARY KEY NOT NULL
  );
  
  CREATE TABLE "payload"."carriers" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"code" varchar NOT NULL,
  	"name" varchar NOT NULL,
  	"tracking_url_template" varchar NOT NULL,
  	"active" boolean DEFAULT true,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "payload"."shipments" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order_id" integer NOT NULL,
  	"carrier_id" integer,
  	"tracking_number" varchar,
  	"shipped_at" timestamp(3) with time zone,
  	"delivered_at" timestamp(3) with time zone,
  	"incoterm" "payload"."enum_shipments_incoterm",
  	"marked_by_id" integer,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "payload"."payload_locked_documents_rels" ADD COLUMN "carriers_id" integer;
  ALTER TABLE "payload"."payload_locked_documents_rels" ADD COLUMN "shipments_id" integer;
  ALTER TABLE "payload"."carriers_markets" ADD CONSTRAINT "carriers_markets_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "payload"."carriers"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."shipments" ADD CONSTRAINT "shipments_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "payload"."orders"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."shipments" ADD CONSTRAINT "shipments_carrier_id_carriers_id_fk" FOREIGN KEY ("carrier_id") REFERENCES "payload"."carriers"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload"."shipments" ADD CONSTRAINT "shipments_marked_by_id_users_id_fk" FOREIGN KEY ("marked_by_id") REFERENCES "payload"."users"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "carriers_markets_order_idx" ON "payload"."carriers_markets" USING btree ("order");
  CREATE INDEX "carriers_markets_parent_idx" ON "payload"."carriers_markets" USING btree ("parent_id");
  CREATE UNIQUE INDEX "carriers_code_idx" ON "payload"."carriers" USING btree ("code");
  CREATE INDEX "carriers_updated_at_idx" ON "payload"."carriers" USING btree ("updated_at");
  CREATE INDEX "carriers_created_at_idx" ON "payload"."carriers" USING btree ("created_at");
  CREATE INDEX "shipments_order_idx" ON "payload"."shipments" USING btree ("order_id");
  CREATE INDEX "shipments_carrier_idx" ON "payload"."shipments" USING btree ("carrier_id");
  CREATE INDEX "shipments_tracking_number_idx" ON "payload"."shipments" USING btree ("tracking_number");
  CREATE INDEX "shipments_marked_by_idx" ON "payload"."shipments" USING btree ("marked_by_id");
  CREATE INDEX "shipments_updated_at_idx" ON "payload"."shipments" USING btree ("updated_at");
  CREATE INDEX "shipments_created_at_idx" ON "payload"."shipments" USING btree ("created_at");
  ALTER TABLE "payload"."payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_carriers_fk" FOREIGN KEY ("carriers_id") REFERENCES "payload"."carriers"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_shipments_fk" FOREIGN KEY ("shipments_id") REFERENCES "payload"."shipments"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "payload_locked_documents_rels_carriers_id_idx" ON "payload"."payload_locked_documents_rels" USING btree ("carriers_id");
  CREATE INDEX "payload_locked_documents_rels_shipments_id_idx" ON "payload"."payload_locked_documents_rels" USING btree ("shipments_id");`)

  // The three new tables carry orders, addresses of couriers and the audit
  // of who shipped what. They are locked down here rather than by whatever
  // event trigger this particular database happens to have.
  await db.execute(sql`
    ALTER TABLE "payload"."carriers" ENABLE ROW LEVEL SECURITY;
    ALTER TABLE "payload"."carriers_markets" ENABLE ROW LEVEL SECURITY;
    ALTER TABLE "payload"."shipments" ENABLE ROW LEVEL SECURITY;

    DO $$
    DECLARE
      unprotected int;
      policies int;
    BEGIN
      SELECT count(*) INTO unprotected
      FROM pg_tables WHERE schemaname = 'payload' AND NOT rowsecurity;

      SELECT count(*) INTO policies
      FROM pg_policies WHERE schemaname = 'payload';

      IF unprotected <> 0 THEN
        RAISE EXCEPTION 'fulfilment_shipments: % table(s) in schema payload have RLS disabled', unprotected;
      END IF;
      -- Zero policies IS the design: RLS with no policy denies everyone who
      -- respects it. Payload connects as the owner and bypasses it.
      IF policies <> 0 THEN
        RAISE EXCEPTION 'fulfilment_shipments: schema payload has % polic(ies); deny-all expects none', policies;
      END IF;
    END $$;
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "payload"."carriers_markets" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload"."carriers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload"."shipments" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "payload"."carriers_markets" CASCADE;
  DROP TABLE "payload"."carriers" CASCADE;
  DROP TABLE "payload"."shipments" CASCADE;
  ALTER TABLE "payload"."payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_carriers_fk";
  
  ALTER TABLE "payload"."payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_shipments_fk";
  
  ALTER TABLE "payload"."outbox" ALTER COLUMN "effect" SET DATA TYPE text;
  DROP TYPE "payload"."enum_outbox_effect";
  CREATE TYPE "payload"."enum_outbox_effect" AS ENUM('restock_if_applicable', 'send_confirmation_email', 'notify_crm', 'issue_tax_invoice', 'send_tracking_email', 'send_post_sale_email', 'open_withdrawal_window', 'execute_provider_refund', 'send_refund_email', 'issue_credit_note', 'alert_refund_failure', 'alert_payment_conflict', 'notify_sales_lead');
  ALTER TABLE "payload"."outbox" ALTER COLUMN "effect" SET DATA TYPE "payload"."enum_outbox_effect" USING "effect"::"payload"."enum_outbox_effect";
  DROP INDEX "payload"."payload_locked_documents_rels_carriers_id_idx";
  DROP INDEX "payload"."payload_locked_documents_rels_shipments_id_idx";
  ALTER TABLE "payload"."payload_locked_documents_rels" DROP COLUMN "carriers_id";
  ALTER TABLE "payload"."payload_locked_documents_rels" DROP COLUMN "shipments_id";
  DROP TYPE "payload"."enum_carriers_markets";
  DROP TYPE "payload"."enum_shipments_incoterm";`)
}
